# Generated by Django 4.2.23 on 2025-07-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
