# Generated by Django 4.2.23 on 2025-07-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country_code',
        ),
    ]
